### ISSUE TITLE
Non-matching template lines

### ISSUE THREAD

**Issue by camilstaps** [annotation/text-fabric#51]
Is it currently possible to indicate that template lines should not appear in results, i.e. are *non-matching* in the sense of non-matching regular expression groups (`(?:...)`)?

In some cases this can be simulated with quantifiers:

```
verse
	non-matching word lex=KL/
```

would be identical to:

```
verse
/with/
	word lex=KL/
/-/
```

However, I don't see how to express the following:

```
verse
	non-matching clause
		word language=Aramaic lex=HWH[
		word vt=ptca
```

Perhaps it can be done with something like this, but that looks cumbersome:

```
verse
	/with/
		clause
			w1:word
			w2:word
			w1=hwy
			w2=ptc
	/-/
	hwy:word language=Aramaic lex=HWH[
	ptc:word vt=ptca
```

**Comment by dirkroorda** [comment]
So you want the words in the clause to be included in the result, but not the clause itself.
That is not possible as matters stand now. Your work around will not work, because you cannot refer from outside a quantifer to names defined inside a quantifier.

If you issue the query in a program and catch the results, it is trivial to remove the clause node from the result tuple.

What you want can be achieved best by a syntactical addition to the query language. A sign that indicates: do not include the node corresponding to this object in the search results.
For example, a `/` directly following the `clause`.

That is not too difficult. But which use case will justify the effort? You get better displays in the browser and in Jupyter notebooks, and that might be important.

**Comment by camilstaps** [comment]
Thanks for the clarification about the names in quantifiers; that makes sense as well.

Indeed, I was working with the browser when I ran into this. I wanted to make sure that the words were in the same clause, but then having both verse and clause displayed in each result is a bit much. You are right that from a program this doesn't really matter.

**Comment by dirkroorda** [comment]
Done. The new release is online.
