### ISSUE TITLE
Add option to manually upload new features 

### ISSUE THREAD

**Issue by codykingham** [annotation/text-fabric#55]
Text-Fabric Browser should have an option to upload node ID / feature pairings. 

For instance, if I have a .csv file where one column is nodes and another is a string feature, I should be able to click an upload button in TF Browser and upload that .csv into the corpus for further exploration and analysis.

Probably those exported files would get pushed to a new directory on disk? A user could then upload to Github when they feel their features are in a finished state.

**Comment by dirkroorda** [comment]
Nice thing to have indeed.

Let's try to think how this might work.
The user uploads data to the server.
The TF kernel converts the csv data into a bunch of tf files, the names of those files are the column headers of the csv files.
The kernel stores the tf files in the local text-fabric-data directory, under the main data source as a new module named after the csv file.
It then loads this module alongside the already loaded data source. Some of the new data might be in features that also exist in the datasource.
In that case the uploaded values override the original values.

The user can now work with the new data and do all kind of things, also exports.
But the results are not immediately reproducible.
Next time he starts the TF-browser he has to add the local module on the command line, with the :local specifier.

In order to make this data available to others, the webinterface then gives the user an option to download the generated tf files. The user can then put them on github somewhere.
Next time he can call the tf browser with the github location of the module as an extra parameter.

This functionality is likely to break something. The TF browser as a local webinterface does not have problems to store the new data on the filesystem. But if the TF server is served over the internet, it might be undoable to offer this functionality.

**Comment by codykingham** [comment]
I wonder if it would be possible of loading the new feature immediately without a restart of the engine. That would allow for a fast cycle of data construction and analysis. 

For where to put the files: maybe we have two input boxes. 1) location of .csv feature file, 2. location of output. That makes the user immediately aware of where the TF files are going, so she can then decide to upload to Github / other archives as needed.

Online implementations of the system could possibly allow for temporary feature loads? So load a feature on the fly and discard after the session is closed?

**Comment by codykingham** [comment]
or instead of "discarding" the online version could allow you to download the .tf files. Then it also doubles as an online conversion engine. But it does not keep the generated files

**Comment by dirkroorda** [comment]
The TF engine can load data on the fly. It will need to do precomputing. That means, care should be taken that not two users upload the same features. This is really a case where it is premature to implement it online. But the local TF browser can be adapted to handle this.

**Comment by dirkroorda** [comment]
I have not come round to it. It is an interesting thing to have, especially the rapid development using the TF browser is a good use case, because it is indeed missing there, whereas in the notebook you can do this.
However, it burdens the TF browser with things that are difficult to give a proper place and might hinder to use it in online situations.
That's why I refrain from doing this now.
