### ISSUE TITLE
Over-Zealous TF Rate Limit Warning

### ISSUE THREAD

**Issue by codykingham** [annotation/text-fabric#57]
TF now gives rate limit warning in red everytime TF is launched (even if `silent="deep"`). 

![Uploading Screen Shot 2020-04-20 at 11.18.35.png…]()

Shouldn't this warning only occur when a rate limit is exceeded? I do not care to apply for a Github token at the moment.

**Comment by dirkroorda** [comment]
Will have a look. Surely, deep silence should not be disturbed by rate limiting noise. By the way, if you are really intensely working on a corpus, it pays off to use the `:clone` specifier:

```
text-fabric nena:clone --checkout=clone
```

``` python
A = use('nena:clone', checkout='clone')
```

**Comment by dirkroorda** [comment]
To be fixed with version 8 (soon)

**Comment by codykingham** [comment]
Fantastic. And thanks for the tip Dirk.

**Comment by dirkroorda** [comment]
I have dealt with it in the code for v8 by now.

**Comment by dirkroorda** [comment]
> TF now gives rate limit warning in red everytime TF is launched (even if silent="deep").
> 
> 
> 
> Shouldn't this warning only occur when a rate limit is exceeded? I do not care to apply for a Github token at the moment.

It depends.
A user can git clone the data repo of a corpus, then use the checkout='clone' specifier and they'll hardly use the github api. But finding the corpus and cloning it to a place on your system introduces various points of failure.

So for a super-easy first step we query the github api. But the standard rate limit is a bit short, and it is a pity to run into it by surprise. So that's why I issue the current rate limit.

**Comment by codykingham** [comment]
The notification itself is not problematic. But the fact that it issues as a system warning seems too strong (aside from the silencing issue).

**Comment by codykingham** [comment]
I actually quite like that the message tells me how many requests I have left.
