### ISSUE TITLE
Issue with api

### ISSUE THREAD

**Issue by atsmotai** [annotation/text-fabric#83]
Hello,
A quick question: I am attempting to access the etcbc/bhsa. However, when I run "tf etcbc/bhsa" the program fails with the code "AttributeError: 'Api' object has no attribute 'L'"

I have followed the instructions to install jupyterlab and text-fabric using pip. I am working on an Ubuntu/linux system.

Any ideas what I am doing wrong?

**Comment by atsmotai** [comment]
I apologize, I was able to resolve the issue. My system was enforcing case-sensitivity and therefore was not retrieving the app files needed. 

Simply running "tf ETCBC/bhsa" with ETCBC in caps fixed the issue.

Really appreciate the amazing work you've done on this!

**Comment by dirkroorda** [comment]
Hi @atsmotai .

You found the root cause. I apologize for any occurrence in the docs and the tutorials where I still say `... etcbc ...` instead of `... ETCBC ...`

I found a way to search and replace them in the docs, but to do the same in the Jupyter Notebooks is a bit more tricky. Will have a look, though.

Thanks for your encouraging remarks!
